name: Cleanup Merged Branches

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (adjust as needed)
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete Merged Feature Branches
        run: |
          git fetch --prune
          # Get only remote merged branches prefixed with 'feature/'
          branches=$(git branch -r --merged | grep 'origin/feature/' | grep -vE 'HEAD')

          if [ -z "$branches" ]; then
            echo "No merged feature branches to delete."
          else
            for branch in $branches; do
              branch_name=$(echo $branch | sed 's|origin/||')
              echo "Deleting branch: $branch_name"
              git push origin --delete $branch_name
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
