name: Cleanup Merged Branches

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Check Current Time
        id: check_time
        run: |
          current_time=$(date +%H%M)
          cutoff_time=1930  # Set the cutoff time to 5:30 PM (17:30)
          if [ "$current_time" -gt "$cutoff_time" ]; then
            echo "Action will not run after 5:30 PM. Current time is $current_time."
            exit 1  # Exit the workflow without failure
          else
            echo "Proceeding with branch deletion. Current time is $current_time."
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete All Merged Feature Branches
        run: |
          git fetch --prune
          merged_branches=$(git branch -r --merged | grep 'origin/feature/' | grep -vE 'HEAD|main|master')

          if [ -z "$merged_branches" ]; then
             echo "No merged feature branches to delete."
          else
            for branch in $merged_branches; do
            branch_name=$(echo $branch | sed 's|origin/||')
            echo "Deleting merged feature branch: $branch_name"
            git push origin --delete $branch_name
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
