name: Validate Commit Messages

on:
  pull_request:
    branches:
      - develop

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate commit messages
        run: |
          git log --pretty=format:"%s" FETCH_HEAD..HEAD | while read line; do
            if [[ ! "$line" =~ ^(feat|fix|docs|style|refactor|test|chore):\ .{1,100}$ ]]; then
              echo "Invalid commit message format: $line"
              exit 1
            else
              echo "Commit message successfully passed validation: $line"
            fi
          done
