name: Cleanup Merged Branches

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Check Current Time
        id: check_time
        run: |
          current_time=$(date +%H%M)
          cutoff_time=1115  # Set the cutoff time to 5:30 PM (17:30)
          if [ "$current_time" -gt "$cutoff_time" ]; then
            echo "Action will not run after 5:30 PM. Current time is $current_time."
            exit 1  # Exit the workflow without failure
          else
            echo "Proceeding with branch deletion. Current time is $current_time."
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete Merged Feature Branch
        run: |
          git fetch --prune
          branch_name=${{ github.event.pull_request.head.ref }}
          
          # Check if the branch follows the 'feature/' naming convention
          if [[ $branch_name == feature/* ]]; then
            echo "Deleting merged feature branch: $branch_name"
            git push origin --delete $branch_name
          else
            echo "Branch $branch_name does not match 'feature/' pattern. Skipping deletion."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
